# 异常处理

## 什么是异常处理 (处理异常，报错error)

```python
print(1 / 0)  # 报了0除错误

# 打印结果：
Traceback (most recent call last):
  File "D:/pycharm_project/day07/01异常处理.py", line 18, in <module>
    print(1 / 0)
ZeroDivisionError: division by zero
```

## 捕获异常

```python
try:
    
    print('----1----')
    f = oen('a.txt', 'r')  # 路径不对， 是错误的代码
    print('----2----')
    
except:   # 捕获异常
    pass
    
# 输出结果：
----1----
```

## 捕获具体异常

```python
try:
    1 / 0
    y = input('请输入数字：')
    y += 10
except TypeError as e:
    print('error:', e)
except ZeroDivisionError as a:
    print('error:', a)

print(x + 10)

# 打印结果：
error: division by zero
11
try:
    1 / 0
    y = input('请输入数字：')
    y += 10
except Exception as e:   # 只要捕捉Exception
    print('error:', e)
```

不需要记住具体异常，只要捕捉Exception

## finally (无论是否报错，都会执行finally下的代码)

```python
try:
    1 / 0
    y = input('请输入数字：')
    y += 10
except Exception as e:   # 只要捕捉Exception
    print('error:', e)
finally:    # 无论是否报错，都会执行finally下的代码
    print(1)
```

## raise (可以自定义异常)

```python
s = input('请输入数字：')
# print(s.isalpha())       # isalpha() 如果全是字母，则输出True
if s.isalpha():
    raise TypeError('报错了, 请输入数字')
    
# 打印结果：
Traceback (most recent call last):
  File "D:/test2.py", line 82, in <module>
    raise TypeError('报错了, 请输入数字')
TypeError: 报错了, 请输入数字
```



## 断言assert

```python
assert 1 == 1

try:
    assert 1 == 2
except Exception as e:
    print(e)
```